
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234


  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
              client-id: 77528859697-k4vn1evj81ledfubh8bdbg9s3iei893a.apps.googleusercontent.com
              client-secret: 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
              scope:
              - email
              - profile
          facebook:
            client-id: 1374890453454187
            client-secret: 6cc268873c44d368e89dfde21a16c0d7
            scope:
            - email
            - public_profile
          naver:
            client-id: UpuPrnfI2v90wskIElg7
            client-secret: KZfuX4j2Om
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

